# -*- coding: utf-8 -*-
"""logistic_regression_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194qdkBEMVxItonn3LSMNVbZ1Pmp-9-iU

Dataset is downloaded from Kaggle. Link: https://www.kaggle.com/giripujar/hr-analytics
"""

st.set_page_config(page_title="Employee Retention Predictor", layout="wide")

st.title("Employee Retention Prediction")
st.write("Predict whether an employee is likely to leave the company.")

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("HR_comma_sep.csv")
st.markdown(
    "<h2 style='color:purple'>Data Exploration and Visualization</h2>",
    unsafe_allow_html=True
)
left = df[df.left==1]
left.shape

retained = df[df.left==0]
retained.shape

"""**Average numbers for all columns**"""

df.groupby('left').mean(numeric_only=True)

"""From above table we can draw following conclusions,
<ol>
    <li>**Satisfaction Level**: Satisfaction level seems to be relatively low (0.44) in employees leaving the firm vs the retained ones (0.66)</li>
    <li>**Average Monthly Hours**: Average monthly hours are higher in employees leaving the firm (199 vs 207)</li>
    <li>**Promotion Last 5 Years**: Employees who are given promotion are likely to be retained at firm </li>
</ol>

**Impact of salary on employee retention**
"""

fig = pd.crosstab(df.salary, df.left).plot(kind="bar").get_figure()
st.pyplot(fig)

"""Above bar chart shows employees with high salaries are likely to not leave the company

**Department wise employee retention rate**
"""

pd.crosstab(df.Department,df.left).plot(kind='bar')

st.write(
    "The chart suggests that department has only a small impact on employee retention, "
    "so it is not included in the prediction model."
)
st.markdown(
    """
    <h3 style='color:purple'>Selected Features</h3>
    <ol>
      <li>Satisfaction Level</li>
      <li>Average Monthly Hours</li>
      <li>Promotion Last 5 Years</li>
      <li>Salary</li>
    </ol>
    """,
    unsafe_allow_html=True
)

subdf = df[['satisfaction_level','average_montly_hours','promotion_last_5years','salary']]
subdf.head()

"""**Tackle salary dummy variable**

Salary has all text data. It needs to be converted to numbers and we will use dummy variable for that. Check my one hot encoding tutorial to understand purpose behind dummy variables.
"""

salary_dummies = pd.get_dummies(subdf.salary, prefix="salary")

df_with_dummies = pd.concat([subdf,salary_dummies],axis='columns')

df_with_dummies.head()

"""Now we need to remove salary column which is text data. It is already replaced by dummy variables so we can safely remove it"""

df_with_dummies.drop('salary',axis='columns',inplace=True)
df_with_dummies.head()

X = df_with_dummies
st.write(df.head())

y = df.left

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.3)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

model.predict(X_test)

"""**Accuracy of the model**"""

accuracy = model.score(X_test, y_test)
st.write("Accuracy:", accuracy)
