# -*- coding: utf-8 -*-
"""logistic_regression_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194qdkBEMVxItonn3LSMNVbZ1Pmp-9-iU

Dataset is downloaded from Kaggle. Link: https://www.kaggle.com/giripujar/hr-analytics
"""


# Commented out IPython magic to ensure Python compatibility.
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# %matplotlib inline

st.set_page_config(page_title="Employee Retention Predictor", layout="wide")

st.title("Employee Retention Prediction")
st.write("Predict whether an employee is likely to leave the company.")

df = pd.read_csv("HR_comma_sep.csv")
st.markdown(
    "<h2 style='color:purple'>Data Exploration and Visualization</h2>",
    unsafe_allow_html=True
)
left = df[df.left==1]
retained = df[df.left==0]
col1, col2 = st.columns(2)

with col1:
    st.metric("Employees Left", left.shape[0])

with col2:
    st.metric("Employees Retained", retained.shape[0])

st.subheader("Average Numbers for All Columns")

st.subheader("Average Values")
st.dataframe(df.groupby("left").mean(numeric_only=True))

st.markdown("""
### Conclusions

- **Satisfaction Level:** Employees with lower satisfaction are more likely to leave.
- **Average Monthly Hours:** Employees working more hours are more likely to leave.
- **Promotion in Last 5 Years:** Employees who receive promotions are more likely to stay.
""")

st.subheader("Impact of Salary on Employee Retention")

fig = pd.crosstab(df.salary, df.left).plot(kind="bar").get_figure()
st.pyplot(fig)

st.write(
    "Employees with higher salaries are generally less likely to leave the company."
)

st.subheader("Department-wise Employee Retention Rate")

fig2 = pd.crosstab(df.Department, df.left).plot(kind="bar").get_figure()
st.pyplot(fig2)

st.write(
    "The chart suggests that department has only a small impact on employee retention, "
    "so it is not included in the prediction model."
)
st.markdown(
    """
    <h3 style='color:purple'>Selected Features</h3>
    <ol>
      <li>Satisfaction Level</li>
      <li>Average Monthly Hours</li>
      <li>Promotion Last 5 Years</li>
      <li>Salary</li>
    </ol>
    """,
    unsafe_allow_html=True
)

subdf = df[['satisfaction_level','average_montly_hours','promotion_last_5years','salary']]
st.dataframe(subdf.head())

st.subheader("One-Hot Encoding of Salary")

st.write(
    "Salary is a categorical feature, so it is converted into dummy variables "
    "before training the model."
)


salary_dummies = pd.get_dummies(subdf.salary, prefix="salary")

df_with_dummies = pd.concat([subdf,salary_dummies],axis='columns')

st.dataframe(df_with_dummies.head())

st.write(
    "The original salary column is removed after creating dummy variables."
)
df_with_dummies.drop('salary',axis='columns',inplace=True)
st.dataframe(df_with_dummies.head())

X = df_with_dummies
st.write(df.head())

y = df.left

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.3)


model = LogisticRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)
st.write(predictions)

st.subheader("Model Accuracy")
accuracy = model.score(X_test, y_test)
st.metric("Model Accuracy", f"{accuracy*100:.2f}%")
